// const CHANGE_RANFILTRATOR_TYPE = 'CHANGE_RANFILTRATOR_TYPE';
// const CHANGE_RANFILTRATOR_GENRE = 'CHANGE_RANFILTRATOR_GENRE';

// export { CHANGE_RANFILTRATOR_TYPE, CHANGE_RANFILTRATOR_GENRE };

const CHANGE_RANFILTRATOR_FILTER = 'CHANGE_RANFILTRATOR_FILTER';

export { CHANGE_RANFILTRATOR_FILTER };
